# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class ManagerView(QDialog):
    def setupUi(self, option_manager):
        option_manager.setObjectName("Dialog")
        option_manager.resize(588, 648)
        option_manager.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(option_manager)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(option_manager)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(14, 149, 201, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border: 1px solid #003c5a;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(250, 40, 91, 91))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./App/Images/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ingenieria = QtWidgets.QPushButton(self.frame)
        self.ingenieria.setGeometry(QtCore.QRect(160, 280, 281, 51))
        self.ingenieria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ingenieria.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(44, 132, 132);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(18, 69, 89);\n"
"}\n"
"\n"
"\n"
"")
        self.ingenieria.setDefault(False)
        self.ingenieria.setFlat(False)
        self.ingenieria.setObjectName("ingenieria")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 190, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.supervisor = QtWidgets.QPushButton(self.frame)
        self.supervisor.setGeometry(QtCore.QRect(160, 470, 281, 51))
        self.supervisor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.supervisor.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(44, 132, 132);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(18, 69, 89);\n"
"}")
        self.supervisor.setObjectName("supervisor")
        self.tecnico = QtWidgets.QPushButton(self.frame)
        self.tecnico.setGeometry(QtCore.QRect(160, 370, 281, 51))
        self.tecnico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tecnico.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0, 0, 0,0%);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(44, 132, 132);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgba(18, 69, 89);\n"
"}")
        self.tecnico.setObjectName("tecnico")
        self.salir = QtWidgets.QPushButton(self.frame)
        self.salir.setGeometry(QtCore.QRect(410, 570, 121, 41))
        self.salir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.salir.setStyleSheet("QPushButton{\n"
"    background-color: rgba(rgb(170, 58, 82));\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(143, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(135, 0, 0);\n"
"}")
        self.salir.setObjectName("salir")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(option_manager)
        self.salir.clicked.connect(option_manager.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(option_manager)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ingenieria.setText(_translate("Dialog", "Ingenieria"))
        self.label_2.setText(_translate("Dialog", "Selecciona una Opcion"))
        self.supervisor.setText(_translate("Dialog", "Supervisor"))
        self.tecnico.setText(_translate("Dialog", "Tecnico"))
        self.salir.setText(_translate("Dialog", "SALIR"))
